# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files first for caching
COPY package.json package-lock.json* ./

# Install dependencies (skip scripts as we only need to build)
RUN npm install --production=false --ignore-scripts

# Copy source code
COPY tsconfig.json ./
COPY src/ ./src/
COPY smithery.yaml ./
COPY README.md ./

# Build the project
RUN npm run build

# Expose any port if necessary, but since it's stdio based, not needed.

# Make the server executable
RUN chmod +x dist/index.js

# Set environment variables if needed (LINEAR_API_TOKEN via runtime)
# default token if not provided
ENV LINEAR_API_TOKEN=

# Run the server
CMD ["npm", "start"]
